from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, declarative_base

from app.config import settings

engine = create_engine(settings.database_url, pool_pre_ping=True, future=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def apply_lightweight_schema_patches(bind_engine=None):
    """Best-effort, idempotent ALTER-TABLE patches for columns added to
    existing ORM models after a database was already created via
    `Base.metadata.create_all()`.

    This project deliberately uses `create_all()` instead of Alembic (see the
    module docstring in app/db/models.py): fine for brand-new tables (which
    `create_all()` handles), but `create_all()` never alters an
    *already-existing* table, so a new column added to an existing model
    (e.g. `IncidentEvent.seq`, added for the event-correlation/canary
    features) needs an explicit, idempotent patch here or it silently never
    appears on a database that was created before the column existed --
    exactly the kind of expand-pattern step described in
    docs/agent-design.md's migration-safety guidance. Every statement here
    uses `IF NOT EXISTS` and is safe to run on every startup, on both a
    freshly created database and one that already has the column.

    It also relaxes `incidents.dedup_key` from a DB-level UNIQUE index to a
    plain (non-unique) index. `dedup_key` identifies "the same underlying
    issue", and application logic (`agents.graph.receive_incident`) already
    enforces "at most one *open* incident per dedup_key" by looking up any
    existing non-terminal row before inserting. A DB-level UNIQUE constraint
    was stricter than intended: once the original incident for a dedup_key
    reached a terminal state (RESOLVED/ROLLED_BACK/REJECTED/FAILED), a
    genuinely new recurrence of that same issue would fail to insert with an
    IntegrityError instead of being accepted as a fresh incident. Any
    database created before this fix still has the old unique index and
    needs this patch to drop it.
    """
    engine_to_use = bind_engine or engine
    if engine_to_use.dialect.name != "postgresql":
        return  # SQLite (used by some lightweight tests) creates fresh tables anyway.
    with engine_to_use.begin() as conn:
        conn.execute(text(
            "ALTER TABLE IF EXISTS incident_events "
            "ADD COLUMN IF NOT EXISTS seq INT GENERATED BY DEFAULT AS IDENTITY"
        ))
        conn.execute(text("DROP INDEX IF EXISTS ix_incidents_dedup_key"))
        conn.execute(text(
            "CREATE INDEX IF NOT EXISTS ix_incidents_dedup_key ON incidents (dedup_key)"
        ))
